imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

symfony_cmf_routing_extra:
    dynamic:
        enabled: true


symfony_cmf_simple_cms:
    routing:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page: SymfonyCmfSimpleCmsBundle:Page:index.html.twig
    use_sonata_admin: false

knp_menu:
    twig: true

symfony_cmf_menu:
    use_sonata_admin: false
    menu_basepath: /cms

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

fos_rest:
    view:
        formats:
            rss: true
        templating_formats:
            rss: true
            html: true
        mime_types:
            rss: 'application/rss+xml'

symfony_cmf_create:
    phpcr_odm: true
    #orm: my_document_manager
    rdf_config_dirs:
        - "%kernel.root_dir%/Resources/rdf-mappings"
    base_path: /cms/routes
    cms_path: /cms/simple
    # stanbol_url: custom stanbol url, otherwise defaults to the demo install
