imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

framework:
    secret:          false
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            false
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  en
    session:         false

# Twig Configuration
twig:
    exception_controller: cmf_seo.error.suggestion_provider.controller:showAction
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
cmf_core:
    persistence:
        phpcr:
            enabled: true

cmf_routing:
    dynamic:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page: CmfSimpleCmsBundle:Page:index.html.twig

knp_menu:
    twig: true

cmf_menu:
    voters:
        uri_prefix: true

cmf_seo:
    title: %%content_title%% | Symfony2 CMF
    description: The Symfony2 Content Management Framework. %%content_description%%
    error:
        enable_parent_provider: true
        enable_sibling_provider: true
        templates:
            html: ":error:index.html.twig"
        exclusion_rules:
            - { path: 'excluded' }
    sitemap:
        defaults:
            default_change_frequency: never
            templates:
                xml: ':sitemap:index.xml.twig'
                html: ':sitemap:index.html.twig'
        configurations:
            sitemap: ~
            frequent:
                default_change_frequency: always
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

fos_rest:
    view:
        formats:
            rss: true
        templating_formats:
            rss: true
            html: true
        mime_types:
            rss: 'application/rss+xml'
    format_listener:
        rules:
            - { path: ^/news.rss, priorities: [ rss ], fallback_format: ~, prefer_extension: true }
            - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: true }

sonata_block:
    default_context: [cms]

sonata_seo:
    page:
        title: Welcome | Symfony2 CMF
        metas:
            name:
                description: The Symfony2 Content Management Framework.
                keywords: "CMF, Symfony2, PHPCR"
