imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

cmf_core:
    persistence:
        phpcr:
            enabled: true
    publish_workflow:
        enabled: false

cmf_simple_cms:
    routing:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page: CmfSimpleCmsBundle:Page:index.html.twig

knp_menu:
    twig: true

cmf_menu:
    voters:
        uri_prefix: true

liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

fos_rest:
    view:
        formats:
            rss: true
        templating_formats:
            rss: true
            html: true
        mime_types:
            rss: 'application/rss+xml'
    format_listener:
        rules:
            - { path: ^/news.rss, priorities: [ rss ], fallback_format: ~, prefer_extension: true }
            - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: true }
