security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Acess to the content editing of the website"
            logout:
                path:   /logout
                target: /
                invalidate_session: true

    access_control:
        - { path: ^/login, roles: ROLE_EDITOR }

    providers:
        my_chain_provider:
            chain:
                providers: [my_memory_provider]
        my_memory_provider:
            memory:
                users:
                    editor: { password: %editor_password%, roles: 'ROLE_EDITOR' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
