# added to get the security.context service for the publish workflow
# see https://github.com/symfony-cmf/CoreBundle/issues/104
security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext

#    role_hierarchy:
#        ROLE_EDITOR:      [ROLE_CAN_VIEW_NON_PUBLISHED]
#        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_EDITOR]
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            pattern: ^/
            anonymous: ~
            http_basic:
#                realm: "Secured Demo Area (username: admin, password: admin)"

    #access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
